# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.BigIntegerField(db_index=True, verbose_name='FB_ID')),
                ('firt_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'db_table': 'app_facebook_users',
            },
        ),
    ]
