# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facebook', '0002_auto_20160430_0330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserScores',
            new_name='UserScore',
        ),
    ]
