# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facebook', '0003_auto_20160430_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100, verbose_name='APP_ID')),
            ],
            options={
                'db_table': 'app_facebook_setting',
            },
        ),
    ]
