# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facebook', '0004_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='app_id',
            field=models.CharField(max_length=200, verbose_name='APP_ID'),
        ),
    ]
