# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facebook', '0005_auto_20160430_0342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
        migrations.AlterModelTable(
            name='settings',
            table='app_facebook_settings',
        ),
    ]
